"""new fields in user model

Revision ID: 010d3a74b547
Revises: c2a768dfc09a
Create Date: 2021-12-29 11:12:29.951457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010d3a74b547'
down_revision = 'c2a768dfc09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
