FROM python:3.9.10-slim

RUN useradd --create-home --shell /bin/bash flask_mega_tutorial

WORKDIR /home/flask_mega_tutorial
COPY boot.sh boot.sh
RUN chmod a+x boot.sh
RUN chown -R flask_mega_tutorial:flask_mega_tutorial ./

USER flask_mega_tutorial

COPY requirements.txt requirements.txt
RUN python -m venv venv_flask
RUN venv_flask/bin/pip install -r requirements.txt
RUN venv_flask/bin/pip install gunicorn pymysql cryptography

COPY app app
COPY migrations migrations
COPY flask_mega_tutorial.py config.py ./


ENV FLASK_APP flask_mega_tutorial.py

EXPOSE 5000
ENTRYPOINT [ "./boot.sh" ]